// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2KSsACUZBuYhv45oYwaMzW
// Component: j6rpUSExfK
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: 2KSsACUZBuYhv45oYwaMzW/projectcss
import sty from "./PlasmicJoinVtc.module.css"; // plasmic-import: j6rpUSExfK/css

export type PlasmicJoinVtc__VariantMembers = {};

export type PlasmicJoinVtc__VariantsArgs = {};
type VariantPropType = keyof PlasmicJoinVtc__VariantsArgs;
export const PlasmicJoinVtc__VariantProps = new Array<VariantPropType>();

export type PlasmicJoinVtc__ArgsType = {};
type ArgPropType = keyof PlasmicJoinVtc__ArgsType;
export const PlasmicJoinVtc__ArgProps = new Array<ArgPropType>();

export type PlasmicJoinVtc__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultJoinVtcProps {}

function PlasmicJoinVtc__RenderFunc(props: {
  variants: PlasmicJoinVtc__VariantsArgs;
  args: PlasmicJoinVtc__ArgsType;
  overrides: PlasmicJoinVtc__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = args;

  return (
    <React.Fragment>
      {}

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        />
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicJoinVtc__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicJoinVtc__VariantsArgs;
    args?: PlasmicJoinVtc__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicJoinVtc__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicJoinVtc__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicJoinVtc__ArgProps,
          internalVariantPropNames: PlasmicJoinVtc__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicJoinVtc__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicJoinVtc";
  } else {
    func.displayName = `PlasmicJoinVtc.${nodeName}`;
  }
  return func;
}

export const PlasmicJoinVtc = Object.assign(
  // Top-level PlasmicJoinVtc renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicJoinVtc
    internalVariantProps: PlasmicJoinVtc__VariantProps,
    internalArgProps: PlasmicJoinVtc__ArgProps
  }
);

export default PlasmicJoinVtc;
/* prettier-ignore-end */
